name: YML & Editorial Checkers
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  yml_editorial_checkers:
    runs-on: ubuntu-latest
    container: ruby:3.0-slim
    steps:
    - run: pwd
    - uses: actions/checkout@v3
      with:
       fetch-depth: 1
    - run: gem install rspec
    - name: Run YML and editorial checkers
      run: rspec
    #############
    # IF FAILED #
    #############
    - name:  CURATORS README (Only failures, in a pretty format)
      if: ${{ failure() }}
      run: rspec --only-failures --format documentation
    - name: Report YML checking failures via PR comment
      if: ${{ failure() }}
      uses: thollander/actions-comment-pull-request@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        comment_includes: Beep boop I'm a bot.
        message: |
          Beep boop I'm a bot. Looks like your VHP curation had some problems. Maybe your YML syntax is wrong, maybe you haven't finished the curation.

          Please click on the "Details" link below in the Status Check next to **YML & Editorial Checkers / yml_editorial_checkers (pull_request)**

          Look for **CURATORS README (Only failures, in a pretty format)**

    ##############
    # IF success #
    ##############
    - name: Report YML checking success via PR comment
      if: ${{ success() }}
      uses: thollander/actions-comment-pull-request@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        comment_includes: Beep boop I'm a bot.
        message: |
          Beep boop I'm a bot. Looks like your curation is valid!

          Make sure that you've updated `curation_level` to the level you were instructed. This ensures you finished the work we expected.

          If so, then you're done! Thank you so much for your volunteer work.

              -The VHP Team





