name: YML & Editorial Checkers
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  yml_editorial_checkers:
    runs-on: ubuntu-latest
    container: ruby:3.0-slim
    steps:
    - run: pwd
    - uses: actions/checkout@v3
      with:
       fetch-depth: 1
    - run: gem install rspec
    - name: Run YML and editorial checkers
      run: rspec
    #############
    # IF FAILED #
    #############
    - name: Rerun but only failures, save to file
      if: ${{ failure() }}
      run: rspec --only-failures --out tmp/rspec.txt
    - name: Read tmp/rspec.txt file into output
      if: ${{ failure() }}
      id: rpsec_failures
      run: echo "::set-output name=rspec_txt::$(cat tmp/rspec.txt)"
    - name: Report YML checking failures via PR comment
      if: ${{ failure() }}
      uses: thollander/actions-comment-pull-request@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: |
          Beep boop I'm a bot. Looks like your VHP curation had the following problems...

          ${{ steps.outputs.rpsec_failures.rspec_txt }}





