name: YML & Editorial Checkers
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  yml_parses:
    name: Is the CVE YAML syntax valid?
    runs-on: ubuntu-latest
    container: ruby:3.0-slim
    steps:
    - run: pwd
    - uses: actions/checkout@v3
      with:
       fetch-depth: 1
    - run: gem install rspec
    - name: Run YML and editorial checkers
      run: rspec spec/yaml_parses_spec.rb
    #############
    # IF FAILED #
    #############
    - name:  CURATORS README (Only failures, in a pretty format)
      if: ${{ failure() }}
      run: rspec spec/yaml_parses_spec.rb --only-failures --format documentation

  cve_curation_finished:
    name: Are all the questions answered?
    needs: yml_parses
    runs-on: ubuntu-latest
    container: ruby:3.0-slim
    steps:
    - run: pwd
    - uses: actions/checkout@v3
      with:
       fetch-depth: 1
    - run: gem install rspec
    - name: Run YML and editorial checkers
      run: rspec spec/cve_spec.rb
    #############
    # IF FAILED #
    #############
    - name:  CURATORS README (Only failures, in a pretty format)
      if: ${{ failure() }}
      run: rspec --only-failures --format documentation








